/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.shcm.shsupercm.fabric.stonecutter;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

public class SCGradlePlugin implements Plugin<Project> {
    @Override
    public void apply(Project project) {
        project.afterEvaluate(this::afterEvaluate);
    }

    private void afterEvaluate(Project project) {
        
    }
}
