/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.shcm.shsupercm.fabric.stonecutter;

import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.initialization.Settings;
import org.gradle.api.plugins.ExtensionAware;
import org.jetbrains.annotations.NotNull;

public class StonecutterPlugin implements Plugin<ExtensionAware> {
    @Override
    public void apply(@NotNull ExtensionAware dest) {
        Class<?> type;
        if (dest instanceof Settings settings)
            type = StonecutterSettingsGradle.class;
        else if (dest instanceof Project project)
            type = project.getBuildFile().getName().equals("stonecutter.gradle") ?
                    StonecutterControllerGradle.class :
                    StonecutterBuildGradle.class;
        else
            throw new IllegalArgumentException("The Stonecutter plugin may only be applied to Settings and Projects");

        dest.getExtensions().create("stonecutter", type, dest);
    }
}
